# Generated by Django 3.2.13 on 2022-06-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='企画名')),
                ('staff', models.CharField(choices=[('未選択', '未選択'), ('承認', '承認'), ('未承認', '未承認')], max_length=3, verbose_name='担当の許可')),
                ('manager', models.CharField(choices=[('未選択', '未選択'), ('承認', '承認'), ('未承認', '未承認')], max_length=3, verbose_name='課長の許可')),
                ('director', models.CharField(choices=[('未選択', '未選択'), ('承認', '承認'), ('未承認', '未承認')], max_length=3, verbose_name='部長の許可')),
                ('company', models.CharField(choices=[('未選択', '未選択'), ('承認', '承認'), ('未承認', '未承認')], max_length=3, verbose_name='部長の許可')),
            ],
        ),
    ]
